### ISSUE TITLE
spatial_distribution_report quitting from lines 133-145

### ISSUE THREAD

**Issue by LGLGLTM** [akoyabio/phenoptr#6] opened 2019-04-23 13:03 UTC
Returning the error : 

Error: Insufficient values in manual scale. 9 needed but only 8 provided.

at 62%

**Comment by AB-Kent** [comment] 2019-04-23 23:58
I think it is probably limited to eight phenotypes. I'll check, if that is the issue it should be easy to fix.

**Comment by LGLGLTM** [comment] 2019-04-29 10:57
Yes, this is why.

I changed it here : 

#### All cells  

```{r cell_locations}
# Colorbrewer Dark2 palette
dark2 = c('#1b9e77','#d95f02','#7570b3','#e7298a',
          '#66a61e','#e6ab02','#a6761d','#666666')

# If csd doesn't have a Phenotype column, make one
csd2 = make_phenotype_column(csd)
p = ggplot(csd2, aes(x=`Cell X Position`, y=`Cell Y Position`, color=Phenotype))
p = add_scales_and_background(p, background, xlim, ylim)
p = p + geom_point() 
if (length(unique(csd2$Phenotype<=8)))
  p = p + scale_color_manual(values=dark2)
p + labs(title='Locations of all cells')

I placed 9 colors and changed Phenotype<=9 and it worked.

**Comment by AB-Kent** [comment] 2019-04-29 13:07
This was a bug caused by misplaced parentheses in the `if (length...` conditional. Fixed in the above-referenced changeset. With more than 8 phenotypes the report will now use the default ggplot2 color palette.

**Closed by AB-Kent** 2019-04-29 13:07 UTC
