### ISSUE TITLE
Error in consolidation and summary

### ISSUE THREAD

**Issue by SDJ7007** [akoyabio/phenoptr#17] opened 2021-11-11 13:58 UTC
Hello, 

I have downloaded phenoptr by the installation procedure as mentioned but my files are not getting consolidated or summarised. 
I have two projects, and after putting both the merge files in the addins only one HTML file of one project is being produced. May I please know what am I doing wrong?

This is the commands below:
> phenoptrReports:::addin_20_consolidate()

Listening on http://127.0.0.1:7199
Reading "merged_f4-80_sma_cd31_cell_seg_data". 
Data is already in microns, no conversion performed                                                                                                         
Adding Slide ID column to merged_f4-80_sma_cd31_cell_seg_data.txt
Writing report for "merged_f4-80_sma_cd31_cell_seg_data". 
Quitting from lines 174-196 (Cell_seg_summary_report.Rmd) 
Unable to write summary report
 All renaming inputs must be named. 
Reading "mhc2 vim_cell_seg_data". 
Data is already in microns, no conversion performed                                                                                                         
Adding Slide ID column to mhc2 vim_cell_seg_data.txt
Writing report for "mhc2 vim_cell_seg_data". 
geom_path: Each group consists of only one observation. Do you need to adjust the group aesthetic?
geom_path: Each group consists of only one observation. Do you need to adjust the group aesthetic?
Writing consolidated data. 
Writing report for consolidated data.                                                                                  
Quitting from lines 174-196 (Cell_seg_summary_report.Rmd) 
Unable to write summary report
 All renaming inputs must be named. 
Done! 

Kindly please do let me know where am I going wrong?
i have used the updated versions of R, R studio as well as phenoptr. 
Thank you

**Comment by AB-Kent** [comment] 2021-11-15 13:56
Duplicate of akoyabio/phenoptrReports#54

**Closed by AB-Kent** 2021-11-15 13:56 UTC
